version: '3'
services:
  rancher:
    image: rancher/rancher:v2.7.5
    container_name: rancher
    privileged: true
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./opt/rancher:/var/lib/rancher
